// Generated by CoffeeScript 1.10.0
(function() {
  var __updateCounter, fgFromBg, hexToRgb, placeholderMessage, showMessages, update;

  $(document).ready(function() {
    var chatContainer, countDown, inputContainer, lockBtn, lockInterval, lockOverlay, lockScreen, lockTimer, logoutBtn, overlay, sendBtn, sendOnEnter, sendOnEnterCheckbox, unlockBtn, unlockCallback, unlockInput, updateAllBtn;
    overlay = $(".overlay");
    lockOverlay = $(".lockOverlay");
    countDown = $(".countDown");
    unlockInput = lockOverlay.find("input.unlock");
    unlockBtn = lockOverlay.find("button.unlock");
    chatContainer = $(".chatContainer");
    inputContainer = $(".inputContainer");
    sendOnEnterCheckbox = $("#sendOnEnter");
    lockBtn = $(".lock");
    sendBtn = $(".btn.send");
    updateAllBtn = $(".btn.updateAll");
    logoutBtn = $(".btn.logout");
    lockScreen = function() {
      clearTimeout(lockTimer);
      countDown.text("");
      clearInterval(lockInterval);
      lockOverlay.fadeIn(40);
      unlockInput.focus();
      return true;
    };
    lockTimer = null;
    lockInterval = null;
    sendOnEnter = true;
    inputContainer.find("#message").keyup(function(evt) {
      var msecs;
      if (lockTimer != null) {
        clearTimeout(lockTimer);
      }
      if (lockInterval) {
        clearInterval(lockInterval);
      }
      msecs = 10000;
      lockTimer = setTimeout(lockScreen, msecs);
      lockInterval = setInterval(function() {
        if (msecs > 0) {
          countDown.text(msecs / 1000);
          msecs -= 1000;
        } else {
          countDown.text("");
          clearInterval(lockInterval);
        }
        return true;
      }, 1000);
      if (evt.which === 13 && sendOnEnter) {
        sendBtn.click();
        return false;
      }
      return true;
    });
    sendOnEnterCheckbox.change(function() {
      sendOnEnter = !sendOnEnter;
      return true;
    });
    lockBtn.click(function() {
      lockScreen();
      return true;
    });
    unlockCallback = function(resp) {
      if (resp === "true") {
        lockOverlay.fadeOut(100);
        unlockInput.removeClass("error").val("");
      } else {
        unlockInput.addClass("error");
      }
      return true;
    };
    unlockInput.keyup(function(evt) {
      if (evt.which === 13) {
        $.post("php/api.php?r=unlock", {
          pw: unlockInput.val()
        }, function(resp) {
          return unlockCallback(resp);
        });
      }
      return true;
    });
    unlockBtn.click(function() {
      $.post("php/api.php?r=unlock", {
        pw: unlockInput.val()
      }, function(resp) {
        return unlockCallback(resp);
      });
      return true;
    });
    sendBtn.click(function() {
      var content, textarea;
      textarea = $("#message");
      content = textarea.val();
      if (content.length === 0) {
        textarea[0].focus();
        return true;
      }
      $.post("php/api.php?r=save", {
        n: $("#name").val(),
        m: content
      }, function() {
        $(".message").val("");
        clearTimeout(nextTimeout);
        update();
        return this;
      });
      textarea[0].focus();
      return true;
    });
    updateAllBtn.click(function() {
      overlay.fadeIn(100, function() {
        $.post("php/api.php?r=update_all", function() {
          clearTimeout(nextTimeout);
          chatContainer.empty();
          window.latestTimestamp = null;
          update("update_all");
          overlay.delay(600).fadeOut(100);
          return this;
        });
        return true;
      });
      return true;
    });
    logoutBtn.click(function() {
      $.post("php/api.php?r=logout", function() {
        clearTimeout(nextTimeout);
        open("index.php", "_self");
        return this;
      });
      return true;
    });
    chatContainer.css("height", window.innerHeight - inputContainer.outerHeight() - 40);
    window.latestTimestamp = null;
    update();
    $(window).resize(function() {
      chatContainer.css("height", window.innerHeight - inputContainer.outerHeight() - 40);
      return true;
    });
    return true;
  });

  hexToRgb = function(hex) {
    var result, shorthandRegex;
    shorthandRegex = /^#?([a-f\d])([a-f\d])([a-f\d])$/i;
    hex = hex.replace(shorthandRegex, function(m, r, g, b) {
      return r + r + g + g + b + b;
    });
    result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16)
    };
  };

  fgFromBg = function(hex) {
    var lightness, rgb;
    rgb = hexToRgb(hex);
    lightness = Math.round(((rgb.r * 299) + (rgb.g * 587) + (rgb.b * 114)) / 1000);
    if (lightness > 125) {
      return "black";
    }
    return "white";
  };

  showMessages = function(messages) {
    var alignment, bg, container, date, i, idx, j, len, len1, message, newMessage, textColor, updated, word, words;
    container = $(".chatContainer");
    updated = $("<div class=\"row updated\" />");
    for (i = 0, len = messages.length; i < len; i++) {
      message = messages[i];
      alignment = message.name === $("#name").val() ? "right" : "left";
      date = moment(message.timestamp, "X");
      if (!date.isBefore(new Date(), "day")) {
        bg = "#" + string_to_color(message.name);
      } else {
        bg = "#cccccc";
      }
      textColor = fgFromBg(bg);
      words = message.message.split(" ");
      newMessage = [];
      for (idx = j = 0, len1 = words.length; j < len1; idx = ++j) {
        word = words[idx];
        if (word.slice(0, 5) === "https") {
          newMessage.push("<a style='color: " + textColor + ";' href='" + word + "' target='_blank'>" + (word.slice(8)) + "</a>");
        } else if (word.slice(0, 4) === "http") {
          newMessage.push("<a style='color: " + textColor + ";' href='" + word + "' target='_blank'>" + (word.slice(7)) + "</a>");
        } else {
          newMessage.push(word);
        }
      }
      newMessage = newMessage.join(" ");
      updated.append("<div class=\"col-xs-9 col-md-8 col-lg-7 message " + (alignment === "left" ? "" : "col-xs-push-3 col-md-push-4 col-lg-push-5") + "\" style=\"background-color: " + bg + "; color: " + textColor + ";\">\n    <div class=\"name\">" + message.name + "</div>\n    <div class=\"time\">" + (date.format("HH:mm")) + "</div>\n    <div class=\"content\">" + newMessage + "</div>\n</div>\n<div class=\"clear\" />");
    }
    container.append(updated);
    updated.find(".content").emoticonize();
    updated.slideDown(500, function() {
      var div;
      div = container[0];
      div.scrollTop = div.scrollHeight;
      return true;
    });
    return this;
  };

  __updateCounter = -1;

  placeholderMessage = true;

  update = function(action) {
    if (action == null) {
      action = "update";
    }
    $.post("php/api.php?r=" + action, {
      ts: latestTimestamp
    }, function(response) {
      var place;
      response = JSON.parse(response);
      if (response.length === 0) {
        if (typeof latestTimestamp === "undefined" || latestTimestamp === null) {
          showMessages([
            {
              name: "System",
              message: "...heute noch keine Nachrichten...",
              timestamp: -1
            }
          ]);
          window.latestTimestamp = -1;
          return true;
        }
        return false;
      }
      if (placeholderMessage) {
        $(".name:contains('System')").parent().remove();
        place = false;
      }
      response = response.sort(function(a, b) {
        return a.timestamp - b.timestamp;
      });
      window.latestTimestamp = response[response.length - 1].timestamp;
      showMessages(response);
      return true;
    });
    if (++__updateCounter % 3 === 0) {
      $.post("php/api.php?r=users", function(response) {
        var bg, i, len, user, users, usersDiv;
        users = JSON.parse(response);
        usersDiv = $(".inputContainer .users");
        usersDiv.empty().html("Angemeldete Nutzer: ");
        for (i = 0, len = users.length; i < len; i++) {
          user = users[i];
          bg = "#" + string_to_color(user);
          usersDiv.append("<span class='label' style='background-color: " + bg + "; color: " + (fgFromBg(bg)) + ";'>" + user + "</span>");
        }
        return true;
      });
    }
    window.nextTimeout = setTimeout(update, 10000);
    return this;
  };

}).call(this);
